baseURL = "/"
languageCode = "en-us"
title = "Coding Pals"
assetDir = "static"
googleAnalytics = "UA-33087369-2"
# Site Template By: http://freehtml5.co/
# https://freehtml5.co/twist-free-website-template-using-bootstrap/

[menu]

[[menu.main]]
 	name = "Home"
	url = "home"
	weight = 1

[[menu.main]]
	url	= "services"
	name 	= "Services"
	weight	= 2

# [[menu.main]]
# 	url = "explore"
# 	name 	= "Projects"
# 	weight	= 3

[[menu.main]]
	url = "pricing"
	name 	= "Pricing"
	weight	= 4

[[menu.main]]
	url = "process"
	name 	= "How It Works"
	weight	= 5

[[menu.main]]
	url 	= "contactus"
	name 	= "Contact Us"
	weight	= 6

[[menu.main]]
	url = "faq"
	name 	= "FAQ"
	weight	= 7

[params]
	siteDescription = "Find your coding buddy"
	author = "Kumar Shwetabh"
	keywords = "coding pals, programming buddies, code together, freelancer, javascript, react, vue, html, css, java, go language"
	location = "Bangalore, India"
	email = "codingpals@gmail.com"
	whatsapp = "888 888 8888"
	aboutus = "We are a group of passionate software developers trying to make best use of our skillsets by helping other developers who need any technical support."				
	showTeams = false
	showClients = false
	showProjects = false
	showPricing = true
	showFaqs = true
	showContactUs = true
	showProcess = true

[params.hero]
	heading= "A <span>Companion</span> For Your Coding Journey"
    subheading = """We understand coding is <span>difficult</span> at times and that's why we are here. 
    <br> Start a journey with one of our expert programmers to assist you in your coding job."""

[params.services]
	title = "Services We Offer"
	subtitle = "We are a small group of developers having over a decade of experience in building software solutions for large and small businesses."

[[params.services.service]]
	icon = "icon-screen-desktop"
	heading = "Help with Coding"
	subheading = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

[[params.services.service]]
	icon = "icon-people"
	heading = "Pair Programming"
	subheading = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

[[params.services.service]]
	icon = "icon-loader"
	heading = "Technical Consultation"
	subheading = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

[[params.services.service]]
	icon = "icon-speech-bubble"
	heading = "Peer Code Reviews"
	subheading = "Let our experts review your code and find potential bugs. They may provide suggestions and recommendations on the best practices."

[params.languages]
	title = "We support following programming languages and technology stacks."

[[params.languages.col1]]
	icon = "icon-laptop"
	heading = "Java & J2EE"
	subheading = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

[[params.languages.col1]]
	icon = "icon-cloud-download"
	heading = "JavaScript Frameworks (React, Vue, jQuery)"
	subheading = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

[[params.languages.col1]]
	icon = "icon-hand-paper-o"
	heading = "SQL (MSSQL and Oracle)"
	subheading = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

[[params.languages.col2]]
	icon = "icon-lightbulb-o"
	heading = "Frontend Technologies (HTML5, CSS/CSS3, JavaScript)"
	subheading = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

[[params.languages.col2]]
	icon = "icon-trophy"
	heading = "Other Programming Languages (Python & Go)"
	subheading = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

[params.processes]
	heading = "How does this work"
	subheading = "Everything you need to know before you get started"

[[params.processes.process]]
	title = "You submit the details of your requirement, project, technology stack, etc. through our Contact Us form."

[[params.processes.process]]
	title = "Based on the request and details provided, an expert will be assigned to go over the requirements in detail. This happens through a voice call or chat in whatever way you are comfortable."

[[params.processes.process]]
	title = "The expert will then assess the task. Only if the expert is 100% confident that he will be able to help and contribute fully to the project, he will accept the assignment."

[[params.processes.process]]
	title = "Once you and the technical expert agree to proceed further, provided you are comfortable working with him, you can transfer the money to the expert's account."

[[params.processes.process]]	
	title = "You and the assigned expert can start communicating on the project related needs once the transfer is complete. That's all. No 3rd party involvement or complicated processes."

[params.faqs]
	heading = "Common Questions"
	subheading = "We have got some questions already answered for you"

[[params.faqs.faq]]
	heading = "Common Questions"
	subheading = "You submit the details of your requirement, project, technology stack, etc. through our Contact Us form."

[[params.faqs.faq]]
	heading = "Common Questions"
	subheading = "You submit the details of your requirement, project, technology stack, etc. through our Contact Us form."

[[params.faqs.faq]]
	heading = "Common Questions"
	subheading = "You submit the details of your requirement, project, technology stack, etc. through our Contact Us form."

[[params.faqs.faq]]
	heading = "Common Questions"
	subheading = "You submit the details of your requirement, project, technology stack, etc. through our Contact Us form."

[[params.faqs.faq]]	
	heading = "Common Questions"
	subheading = "You submit the details of your requirement, project, technology stack, etc. through our Contact Us form."
